name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run the action on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false  # Ensure submodules are not an issue

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Build and Deploy
        run: |
          echo "Deployment step goes here"
          # Add your actual build/deployment commands
          git push origin main
