name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ Allows pushing changes
  pages: write     # ✅ Required for GitHub Pages
  id-token: write  # ✅ Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ❗ Prevents GitHub Actions from using default credentials

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/FaZeSnowBee/SvatbaPage.git

      - name: Build and Deploy
        run: |
          echo "Deployment step goes here"
          git push origin main
